### ISSUE TITLE
"Restrict processing" feature

### ISSUE THREAD

**Issue by fedir** [georgringer/gdpr#5]
I would like to propose to implement "Restrict processing" feature (it's also one of the most important points of GDPR).

Objective :

* On the request of the user it's private information should not be available for webmasters in backend, to site visitors in frontend, and should not be exported via TYPO3 backend (CSV) etc.

How it could work :

* Each frontend user should be able to restrict the access to it's own data
* Extend TCA to classify selected tables / fields as "private data" sensible
* Hide sensible columns in the Backend from webmasters
* Extend permission system
* Hide sensible columns in the Frontend from internautes
* Extend frontend rendering system
* Extend data access API, adding additional conditions, where privacy protected fields will be empty, when exported

Ressources:

https://gdpr-info.eu/art-18-gdpr/
https://techblog.bozho.net/gdpr-practical-guide-developers/

**Comment by georgringer** [comment]
This is all solved with the extension, what do you miss?
